# Numpy Library Using In Python :-------

- Commands :--
 - pip install numpy (open the file library then write in terminal)
 - pip show numpy (all open the file write in  terminal)
 - we write on 2D Array  

In [296]:
import numpy as np

In [297]:
# we work on 2d array
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [298]:
n2 = np.array([2, 3, 4, 5])
print(n2)
print(type(n2))

[2 3 4 5]
<class 'numpy.ndarray'>


In [299]:
n1

array([1, 2, 3, 4])

In [300]:
# normal list
x = []
#dir(x)
len(dir(x))

47

In [301]:
x = []
len(dir(x))

47

In [302]:
# numpy
len(dir(n1))

165

In [303]:
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [304]:
n1.shape

(4,)

In [305]:
# to build the matrix
n2 = np.array([[1,2,3],[2,3,4]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


 # Creating Martrix :------
 - arange
 - linspace
 - random.rand
 - random.randn
 - random. randint
 - eye
 - ones
 - zeros


In [342]:
np.arange(-10, 20, .3)

array([-10. ,  -9.7,  -9.4,  -9.1,  -8.8,  -8.5,  -8.2,  -7.9,  -7.6,
        -7.3,  -7. ,  -6.7,  -6.4,  -6.1,  -5.8,  -5.5,  -5.2,  -4.9,
        -4.6,  -4.3,  -4. ,  -3.7,  -3.4,  -3.1,  -2.8,  -2.5,  -2.2,
        -1.9,  -1.6,  -1.3,  -1. ,  -0.7,  -0.4,  -0.1,   0.2,   0.5,
         0.8,   1.1,   1.4,   1.7,   2. ,   2.3,   2.6,   2.9,   3.2,
         3.5,   3.8,   4.1,   4.4,   4.7,   5. ,   5.3,   5.6,   5.9,
         6.2,   6.5,   6.8,   7.1,   7.4,   7.7,   8. ,   8.3,   8.6,
         8.9,   9.2,   9.5,   9.8,  10.1,  10.4,  10.7,  11. ,  11.3,
        11.6,  11.9,  12.2,  12.5,  12.8,  13.1,  13.4,  13.7,  14. ,
        14.3,  14.6,  14.9,  15.2,  15.5,  15.8,  16.1,  16.4,  16.7,
        17. ,  17.3,  17.6,  17.9,  18.2,  18.5,  18.8,  19.1,  19.4,
        19.7])

In [306]:
np.arange(-10, 10, .2)

array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [307]:
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [308]:
x = np.arange(10, 2, 15)

In [309]:
x.shape

(0,)

In [310]:
# len space

y = np.linspace(1, 5, 10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [311]:

y = np.linspace(1, 5, 25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [312]:
#np.random.rand()
np.random.rand(3,3)

array([[0.5320322 , 0.35992089, 0.85149165],
       [0.77783591, 0.96333853, 0.03112582],
       [0.07060743, 0.16030128, 0.77151203]])

In [343]:
np.random.rand(2, 2)

array([[0.39136497, 0.516017  ],
       [0.80938863, 0.6463537 ]])

In [313]:
np.random.randn(10)

array([-0.31048595, -1.35185274,  1.08110345, -2.25896273,  0.06164761,
       -1.37918875, -0.64394728,  1.66925347, -0.82939353,  0.43426078])

In [344]:
np.random.randn(30)

array([-2.24047774, -0.51662024, -0.34793258, -1.81309152,  1.18204501,
       -0.59200558,  0.83590242,  0.67801152, -0.46997508,  0.98242389,
        0.47392783, -0.04602279,  1.34603416, -0.72110837, -0.25465039,
       -0.26737445, -1.06504655, -0.31472327,  0.48416836,  0.83170836,
        0.31049629,  1.35918165, -0.24585608, -1.52239878,  0.50039101,
        0.74209567, -0.33993233,  0.04291046,  1.15807001,  1.87347986])

In [314]:
np.random.randn(20)

array([-1.08970918,  0.53240357,  0.13530079, -0.05278367, -0.45423877,
       -0.58971141, -0.52929274, -0.52759901, -0.23628114,  0.4527103 ,
        0.36897063, -0.18586773, -0.84243383, -0.8769018 , -1.53200962,
        0.63141493, -0.53018924,  0.66978344,  1.2705765 ,  0.08492519])

In [315]:
# number came in random without excluding 5
np.random.randint(1, 5, (5,5))

array([[4, 4, 4, 1, 1],
       [2, 3, 1, 1, 3],
       [2, 2, 1, 1, 1],
       [1, 2, 2, 3, 1],
       [1, 3, 1, 2, 3]])

In [345]:
np.random.randint(1, 5,(5,5))

array([[4, 1, 4, 4, 1],
       [2, 1, 3, 3, 1],
       [1, 1, 2, 3, 2],
       [3, 2, 4, 4, 1],
       [2, 4, 3, 4, 3]])

In [316]:
x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (3,2))
print(x)
print(y)

[[1 2]
 [3 8]
 [4 5]]
[[2 7]
 [6 8]
 [5 2]]


In [317]:
# increase the number in matrix 5
x + 5

array([[ 6,  7],
       [ 8, 13],
       [ 9, 10]])

In [318]:
# multiply the matrix
x * 2

array([[ 2,  4],
       [ 6, 16],
       [ 8, 10]])

In [319]:
# add the matrix

x + y

array([[ 3,  9],
       [ 9, 16],
       [ 9,  7]])

In [320]:
# subtract the matrix

x - y

array([[-1, -5],
       [-3,  0],
       [-1,  3]])

In [321]:
# transpose the matrix

x.dot(y.T)

array([[16, 22,  9],
       [62, 82, 31],
       [43, 64, 30]])

In [348]:
x.dot(y.T)

array([[16, 22,  9],
       [62, 82, 31],
       [43, 64, 30]])

In [322]:
# matrix in trignometry form
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001,  0.98935825],
       [-0.7568025 , -0.95892427]])

In [349]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001,  0.98935825],
       [-0.7568025 , -0.95892427]])

In [323]:
# stastics , multiply

print(x.sum())
print(x.mean())
print(x.std())

23
3.8333333333333335
2.266911751455907


In [350]:
print(x.sum())
print(x.mean())
print(x.std())

23
3.8333333333333335
2.266911751455907


In [346]:
a = np.linspace(0, 5, 50)
print(a.shape)
a2 = a.reshape(10, 5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [325]:
a2.reshape(5,5, 2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [353]:
a2.reshape(5, 5, 2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [326]:
a2.reshape(5, 5, 2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [327]:
m =np.random.randint(1, 10, (10, 10))
print(m)

[[7 6 1 5 6 8 4 1 5 1]
 [6 1 9 4 2 1 1 9 7 8]
 [5 1 6 2 3 3 8 1 6 2]
 [9 6 3 4 3 7 4 4 2 3]
 [2 2 2 7 9 2 4 9 8 2]
 [7 4 2 4 6 1 1 3 9 1]
 [3 3 1 6 9 1 9 1 2 9]
 [3 5 1 4 6 3 5 9 4 9]
 [6 8 1 8 5 3 2 4 5 8]
 [7 7 4 1 9 3 1 6 6 8]]


In [328]:
print(m[0,0]) # first row first colom
print(m[0,-1]) # first , last coloum
print(m[-1,0])
print(m[-1,-1])

7
1
7
8


In [347]:
print(m[0])
print(m[0,-1])
print(m[-1,0])
print(m[-1,-1])

[7 6 1 5 6 8 4 1 5 1]
1
7
8


In [329]:
print(m[0]) # first row
print(m[1]) # second row
print(m[-1]) # last row
print(m[:3]) # first 3 row
print(m[-3:]) # last 3 row

[7 6 1 5 6 8 4 1 5 1]
[6 1 9 4 2 1 1 9 7 8]
[7 7 4 1 9 3 1 6 6 8]
[[7 6 1 5 6 8 4 1 5 1]
 [6 1 9 4 2 1 1 9 7 8]
 [5 1 6 2 3 3 8 1 6 2]]
[[3 5 1 4 6 3 5 9 4 9]
 [6 8 1 8 5 3 2 4 5 8]
 [7 7 4 1 9 3 1 6 6 8]]


In [330]:
# To find first coloum

print(m[:,0]) # first coloum
print(m[:,-1]) # last colom
print(m[:,:3]) # first 3 colom 
print(m[:,-3:]) # last 3 colom




[7 6 5 9 2 7 3 3 6 7]
[1 8 2 3 2 1 9 9 8 8]
[[7 6 1]
 [6 1 9]
 [5 1 6]
 [9 6 3]
 [2 2 2]
 [7 4 2]
 [3 3 1]
 [3 5 1]
 [6 8 1]
 [7 7 4]]
[[1 5 1]
 [9 7 8]
 [1 6 2]
 [4 2 3]
 [9 8 2]
 [3 9 1]
 [1 2 9]
 [9 4 9]
 [4 5 8]
 [6 6 8]]


In [354]:
# specific colom if you  want the any colom

print(m[:, [0, 2, 3, 5]])


[[7 1 5 8]
 [6 9 4 1]
 [5 6 2 3]
 [9 3 4 7]
 [2 2 7 2]
 [7 2 4 1]
 [3 1 6 1]
 [3 1 4 3]
 [6 1 8 3]
 [7 4 1 3]]


- filtering

In [332]:
m

array([[7, 6, 1, 5, 6, 8, 4, 1, 5, 1],
       [6, 1, 9, 4, 2, 1, 1, 9, 7, 8],
       [5, 1, 6, 2, 3, 3, 8, 1, 6, 2],
       [9, 6, 3, 4, 3, 7, 4, 4, 2, 3],
       [2, 2, 2, 7, 9, 2, 4, 9, 8, 2],
       [7, 4, 2, 4, 6, 1, 1, 3, 9, 1],
       [3, 3, 1, 6, 9, 1, 9, 1, 2, 9],
       [3, 5, 1, 4, 6, 3, 5, 9, 4, 9],
       [6, 8, 1, 8, 5, 3, 2, 4, 5, 8],
       [7, 7, 4, 1, 9, 3, 1, 6, 6, 8]])

In [355]:
m

array([[7, 6, 1, 5, 6, 8, 4, 1, 5, 1],
       [6, 1, 9, 4, 2, 1, 1, 9, 7, 8],
       [5, 1, 6, 2, 3, 3, 8, 1, 6, 2],
       [9, 6, 3, 4, 3, 7, 4, 4, 2, 3],
       [2, 2, 2, 7, 9, 2, 4, 9, 8, 2],
       [7, 4, 2, 4, 6, 1, 1, 3, 9, 1],
       [3, 3, 1, 6, 9, 1, 9, 1, 2, 9],
       [3, 5, 1, 4, 6, 3, 5, 9, 4, 9],
       [6, 8, 1, 8, 5, 3, 2, 4, 5, 8],
       [7, 7, 4, 1, 9, 3, 1, 6, 6, 8]])

In [333]:
m < 5 # boolean filter

array([[False, False,  True, False, False, False,  True,  True, False,
         True],
       [False,  True, False,  True,  True,  True,  True, False, False,
        False],
       [False,  True, False,  True,  True,  True, False,  True, False,
         True],
       [False, False,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True, False, False,  True,  True, False, False,
         True],
       [False,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [ True,  True,  True, False, False,  True, False,  True,  True,
        False],
       [ True, False,  True,  True, False,  True, False, False,  True,
        False],
       [False, False,  True, False, False,  True,  True,  True, False,
        False],
       [False, False,  True,  True, False,  True,  True, False, False,
        False]])

In [334]:
m > 8

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False,  True, False, False,
         True],
       [False, False, False, False, False, False, False,  True, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False]])

In [335]:
m[m < 5]

array([1, 4, 1, 1, 1, 4, 2, 1, 1, 1, 2, 3, 3, 1, 2, 3, 4, 3, 4, 4, 2, 3,
       2, 2, 2, 2, 4, 2, 4, 2, 4, 1, 1, 3, 1, 3, 3, 1, 1, 1, 2, 3, 1, 4,
       3, 4, 1, 3, 2, 4, 4, 1, 3, 1])

In [356]:
m[m>3]

array([7, 6, 5, 6, 8, 4, 5, 6, 9, 4, 9, 7, 8, 5, 6, 8, 6, 9, 6, 4, 7, 4,
       4, 7, 9, 4, 9, 8, 7, 4, 4, 6, 9, 6, 9, 9, 9, 5, 4, 6, 5, 9, 4, 9,
       6, 8, 8, 5, 4, 5, 8, 7, 7, 4, 9, 6, 6, 8])

In [336]:
m[m > 3]

array([7, 6, 5, 6, 8, 4, 5, 6, 9, 4, 9, 7, 8, 5, 6, 8, 6, 9, 6, 4, 7, 4,
       4, 7, 9, 4, 9, 8, 7, 4, 4, 6, 9, 6, 9, 9, 9, 5, 4, 6, 5, 9, 4, 9,
       6, 8, 8, 5, 4, 5, 8, 7, 7, 4, 9, 6, 6, 8])

In [337]:
# filter used in data analysis
m[(m > 3) & (m <=6)]

array([6, 5, 6, 4, 5, 6, 4, 5, 6, 6, 6, 4, 4, 4, 4, 4, 4, 6, 6, 5, 4, 6,
       5, 4, 6, 5, 4, 5, 4, 6, 6])

In [338]:
# numpy documents
m.flatten?

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Numpy Revision :--

In [357]:
import numpy as np

In [ ]:
arr= np.array([[1, 2, 3, 4, 5]])

In [ ]:
arr

array([[1, 2, 3, 4, 5]])

In [ ]:
print(arr)

[[1 2 3 4 5]]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 2, 3, 4, 5]])
print(arr)

[[1 2 3 4 5]]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [358]:
import numpy as np

In [359]:
print(np.__version__)

1.25.2


In [ ]:
myarr = np.array([[1, 2, 3, 4, 5]])

In [ ]:
myarr[0,1]

2

In [ ]:
myarr.shape

(1, 5)

In [ ]:
myarr.dtype

dtype('int32')

In [ ]:
# change the value in place of 
myarr[0, 1] = 44

In [ ]:
myarr

array([[ 1, 44,  3,  4,  5]])

In [360]:
myarr[0, 1] = 45

In [361]:
myarr

array([[ 1, 45,  3,  4,  5]])

#  Array Creation : Conversion from other Python Structures

In [ ]:
listarray = np.array([[1, 2, 3], [4, 5, 6],[6, 8, 9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 8, 9]])

In [ ]:
listarray.dtype

dtype('int32')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
# 2D Array :--
arr = np.array([[1, 2, 3], [3, 4, 5]])
 
 

In [ ]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr = np.array({23, 45, 66})

In [ ]:
arr

array({66, 45, 23}, dtype=object)

In [ ]:
arr.dtype

dtype('O')

In [ ]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
zeros.shape

(2, 5)

In [ ]:
zeros.size

10

In [ ]:
rng = np.arange(15)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
rng.dtype

dtype('int32')

In [ ]:
rng = np.arange(20)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [339]:
rng.dtype

dtype('int32')

In [340]:
lspace = np.linspace(1, 5, 10)

In [341]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
lspace.dtype

dtype('float64')

In [362]:
lspace = np.linspace(1, 4, 4)

In [363]:
lspace

array([1., 2., 3., 4.])

In [364]:
lspace = np.linspace(1, 5, 20)
lspace

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [365]:
lspace.dtype

dtype('float64')

In [366]:
lspace = np.linspace(1, 10, 30)

In [367]:
lspace

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [368]:
lspace.dtype

dtype('float64')

In [369]:
emp = np.empty((4, 6))

In [370]:
emp

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000, -2.49895341e-310,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000, -2.55327647e-310]])

In [371]:
emp.dtype

dtype('float64')

In [372]:
emp_like = np.empty_like(lspace)

In [373]:
emp_like

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [ ]:
ide = np.identity(45)

In [ ]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
arr = np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [392]:
arr = arr.ravel()

In [393]:
arr.shape

(9,)

In [394]:
x = ([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

In [395]:
arr = np.array(x)

In [396]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [397]:
arr.sum(axis=0)

array([12, 15, 18])

In [398]:
arr.sum(axis=1)

array([ 6, 15, 24])

# Attribute

In [399]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [390]:
arr.flat

In [391]:
for item in arr.flat:
    print(item)


1
2
3
4
5
6
7
8
9


In [384]:
# know the number of dimension

arr.ndim

2

In [400]:
# number of bytes
arr.nbytes

36

# Methods

In [386]:
one = np.array([[12, 34, 56]])

In [387]:
one

array([[12, 34, 56]])

In [388]:
# it is give the max element of indexing

one.argmax()

2

In [389]:
one.argmin()

0

In [ ]:
# give the indexing in a increasing order :--
one.argsort()

array([[0, 1, 2]], dtype=int64)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.argmin()

0

In [ ]:
arr.argmax()

8

In [ ]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [ ]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [ ]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [ ]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[1, 2, 3],
       [2, 3, 6],
       [4, 3, 1]])

In [ ]:
arr + arr2

array([[ 2,  4,  6],
       [ 6,  8, 12],
       [11, 11, 10]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[1, 2, 3],
       [2, 3, 6],
       [4, 3, 1]])

In [ ]:
arr * arr2

array([[ 1,  4,  9],
       [ 8, 15, 36],
       [28, 24,  9]])

In [ ]:
arr - arr2

array([[0, 0, 0],
       [2, 2, 0],
       [3, 5, 8]])

In [ ]:
(arr*arr2) + (arr + arr2) 

array([[ 3,  8, 15],
       [14, 23, 48],
       [39, 35, 19]])

In [ ]:
# squareroot of element :--

np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
arr.max()

9

In [ ]:
arr.min()

1

In [ ]:
arr.sum()

45

# Finding of elements :--

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [ ]:
type(np.where(arr>5))

tuple

In [ ]:
# count the non zero element 
np.count_nonzero(arr)

9

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
arr[1, 2] = 0

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [ ]:
import sys

In [ ]:
py_arr = [12, 45, 77, 88]

In [ ]:
np_arr=np.array(py_arr)

In [ ]:
# size of python array
sys.getsizeof(1) * len(py_arr)



112

In [ ]:
# numpy size of array 
np_arr.itemsize * np_arr.size

16

In [401]:
a =np.array([[1, 2, 3], [2, 3, 4]])
a


array([[1, 2, 3],
       [2, 3, 4]])

In [402]:
a.T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [403]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [404]:
a.T

array([1, 2, 3, 4, 5])