# Numpy Library Using In Python :-------

- Commands :--
 - pip install numpy (open the file library then write in terminal)
 - pip show numpy (all open the file write in  terminal)
 - we write on 2D Array  

In [1]:
import numpy as np

In [2]:
# we work on 2d array
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
# normal list
x = []
#dir(x)
len(dir(x))

47

In [5]:
# numpy
len(dir(n1))

165

In [6]:
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [10]:
n1.shape

(4,)

In [11]:
# to build the matrix
n2 = np.array([[1,2,3],[2,3,4]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


 # Creating Martrix :------
 - arange
 - linspace
 - random.rand
 - random.randn
 - random. randint
 - eye
 - ones
 - zeros


In [12]:
np.arange(-10, 10, .2)

array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [14]:
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [15]:
# len space

y = np.linspace(1, 5, 10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [17]:

y = np.linspace(1, 5, 25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [21]:
#np.random.rand()
np.random.rand(3,3)

array([[0.11862748, 0.82067473, 0.88438138],
       [0.77900328, 0.62364401, 0.74342723],
       [0.70868338, 0.12870691, 0.74787502]])

In [22]:
np.random.randn(10)

array([-0.69890113,  0.39105104,  1.10084441,  0.82941919,  0.39736411,
        1.88986196,  1.24956506, -0.37565402,  0.17070174, -0.46154819])

In [25]:
np.random.randn(20)

array([ 1.87987151, -1.16694927, -0.07653462, -1.57031738, -0.87487111,
       -1.7993188 , -0.0379631 , -1.6868526 , -1.34579795,  0.83202517,
        0.41510933, -0.10823352,  0.48109086,  1.03400034,  0.98226618,
       -0.14807138,  1.31469718,  0.73879224, -0.50475239,  0.89813959])

In [27]:
# number came in random without excluse 5
np.random.randint(1, 5, (5,5))

array([[4, 3, 1, 2, 1],
       [3, 1, 1, 3, 1],
       [4, 2, 3, 2, 4],
       [3, 4, 2, 2, 1],
       [4, 3, 2, 1, 3]])

In [30]:
x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (3,2))
print(x)
print(y)

[[5 5]
 [3 1]
 [6 7]]
[[5 5]
 [3 3]
 [9 3]]


In [31]:
# increase the number in matrix 5
x + 5

array([[10, 10],
       [ 8,  6],
       [11, 12]])

In [32]:
# multiply the matrix
x * 2

array([[10, 10],
       [ 6,  2],
       [12, 14]])

In [33]:
# add the matrix

x + y

array([[10, 10],
       [ 6,  4],
       [15, 10]])

In [34]:
# subtract the matrix

x - y

array([[ 0,  0],
       [ 0, -2],
       [-3,  4]])

In [35]:
# transpose the matrix

x.dot(y.T)

array([[50, 30, 60],
       [20, 12, 30],
       [65, 39, 75]])

In [36]:
# matrix in trignometry form
np.sin(x)

array([[-0.95892427, -0.95892427],
       [ 0.14112001,  0.84147098],
       [-0.2794155 ,  0.6569866 ]])

In [37]:
# stastics , multiply

print(x.sum())
print(x.mean())
print(x.std())

27
4.5
1.9790570145063195
