# Numpy Library Using In Python :-------

- Commands :--
 - pip install numpy (open the file library then write in terminal)
 - pip show numpy (all open the file write in  terminal)
 - we write on 2D Array  

In [1]:
import numpy as np

In [2]:
# we work on 2d array
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
# normal list
x = []
#dir(x)
len(dir(x))

47

In [5]:
# numpy
len(dir(n1))

165

In [6]:
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [7]:
n1.shape

(4,)

In [8]:
# to build the matrix
n2 = np.array([[1,2,3],[2,3,4]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


 # Creating Martrix :------
 - arange
 - linspace
 - random.rand
 - random.randn
 - random. randint
 - eye
 - ones
 - zeros


In [9]:
np.arange(-10, 10, .2)

array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [10]:
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [11]:
# len space

y = np.linspace(1, 5, 10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [17]:

y = np.linspace(1, 5, 25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [12]:
#np.random.rand()
np.random.rand(3,3)

array([[0.59498272, 0.86148876, 0.9364877 ],
       [0.04416395, 0.67267426, 0.94639442],
       [0.54946397, 0.37684625, 0.83978248]])

In [13]:
np.random.randn(10)

array([ 0.37351701, -0.20298553, -1.24924581,  0.89526016, -0.83521106,
       -0.77046969,  2.61435495,  1.09176479, -0.33443362,  1.2773233 ])

In [14]:
np.random.randn(20)

array([ 1.51678589,  0.53392066, -0.83464613, -0.65059421, -0.31950888,
        1.27819067,  1.69706246,  0.49434237,  0.33390881, -0.10796989,
        0.04645268,  1.17074653, -0.20237899,  1.30777674,  0.74506228,
        0.72200497,  1.07521223, -2.03015148, -0.73635967,  0.34190571])

In [27]:
# number came in random without excluse 5
np.random.randint(1, 5, (5,5))

array([[4, 3, 1, 2, 1],
       [3, 1, 1, 3, 1],
       [4, 2, 3, 2, 4],
       [3, 4, 2, 2, 1],
       [4, 3, 2, 1, 3]])

In [30]:
x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (3,2))
print(x)
print(y)

[[5 5]
 [3 1]
 [6 7]]
[[5 5]
 [3 3]
 [9 3]]


In [31]:
# increase the number in matrix 5
x + 5

array([[10, 10],
       [ 8,  6],
       [11, 12]])

In [32]:
# multiply the matrix
x * 2

array([[10, 10],
       [ 6,  2],
       [12, 14]])

In [33]:
# add the matrix

x + y

array([[10, 10],
       [ 6,  4],
       [15, 10]])

In [34]:
# subtract the matrix

x - y

array([[ 0,  0],
       [ 0, -2],
       [-3,  4]])

In [35]:
# transpose the matrix

x.dot(y.T)

array([[50, 30, 60],
       [20, 12, 30],
       [65, 39, 75]])

In [36]:
# matrix in trignometry form
np.sin(x)

array([[-0.95892427, -0.95892427],
       [ 0.14112001,  0.84147098],
       [-0.2794155 ,  0.6569866 ]])

In [15]:
# stastics , multiply

print(x.sum())
print(x.mean())
print(x.std())

-10.000000000003503
-0.10000000000003503
5.773214009544403


In [18]:
a = np.linspace(0,5, 50)
print(a.shape)
a2 = a.reshape(10, 5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [19]:
a2.reshape(5,5, 2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [38]:
a2.reshape(5, 5, 2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [50]:
m =np.random.randint(1, 10, (10, 10))
print(m)

[[4 8 2 8 6 6 6 1 7 4]
 [3 2 8 4 7 4 6 9 9 7]
 [5 7 9 6 9 2 2 3 3 1]
 [9 9 8 8 5 9 4 2 4 3]
 [3 8 1 7 6 8 4 6 1 1]
 [7 2 2 6 7 3 3 1 3 4]
 [4 1 6 7 9 6 4 7 7 6]
 [5 8 6 9 8 6 9 3 1 2]
 [7 9 5 5 2 9 6 7 6 2]
 [4 7 9 3 8 2 6 1 4 4]]


In [51]:
print(m[0,0]) # first row first colom
print(m[0,-1]) # first , last coloum
print(m[-1,0])
print(m[-1,-1])

4
4
4
4


In [49]:
print(m[0]) # first row
print(m[1]) # second row
print(m[-1]) # last row
print(m[:3]) # first 3 row
print(m[-3:]) # last 3 row

[8 5 4 7 1 5 6 8 4 2]
[1 1 7 4 4 7 5 5 8 4]
[2 5 6 6 6 9 3 8 2 9]
[[8 5 4 7 1 5 6 8 4 2]
 [1 1 7 4 4 7 5 5 8 4]
 [5 7 1 6 7 1 1 9 9 9]]
[[8 9 8 8 5 6 2 3 6 5]
 [2 2 4 9 3 5 7 1 1 7]
 [2 5 6 6 6 9 3 8 2 9]]


In [53]:
# to find first coloum

print(m[:,0]) # first coloum
print(m[:,-1]) # last colom
print(m[:,:3]) # first 3 colom 
print(m[:,-3:]) # last 3 colom




[4 3 5 9 3 7 4 5 7 4]
[4 7 1 3 1 4 6 2 2 4]
[[4 8 2]
 [3 2 8]
 [5 7 9]
 [9 9 8]
 [3 8 1]
 [7 2 2]
 [4 1 6]
 [5 8 6]
 [7 9 5]
 [4 7 9]]
[[1 7 4]
 [9 9 7]
 [3 3 1]
 [2 4 3]
 [6 1 1]
 [1 3 4]
 [7 7 6]
 [3 1 2]
 [7 6 2]
 [1 4 4]]


In [54]:
# spcific colom if you  want the any colom

print(m[:, [0, 2, 3, 5]])


[[4 2 8 6]
 [3 8 4 4]
 [5 9 6 2]
 [9 8 8 9]
 [3 1 7 8]
 [7 2 6 3]
 [4 6 7 6]
 [5 6 9 6]
 [7 5 5 9]
 [4 9 3 2]]


- filtering

In [55]:
m

array([[4, 8, 2, 8, 6, 6, 6, 1, 7, 4],
       [3, 2, 8, 4, 7, 4, 6, 9, 9, 7],
       [5, 7, 9, 6, 9, 2, 2, 3, 3, 1],
       [9, 9, 8, 8, 5, 9, 4, 2, 4, 3],
       [3, 8, 1, 7, 6, 8, 4, 6, 1, 1],
       [7, 2, 2, 6, 7, 3, 3, 1, 3, 4],
       [4, 1, 6, 7, 9, 6, 4, 7, 7, 6],
       [5, 8, 6, 9, 8, 6, 9, 3, 1, 2],
       [7, 9, 5, 5, 2, 9, 6, 7, 6, 2],
       [4, 7, 9, 3, 8, 2, 6, 1, 4, 4]])

In [56]:
m < 5 # boolean filter

array([[ True, False,  True, False, False, False, False,  True, False,
         True],
       [ True,  True, False,  True, False,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True, False,  True, False, False, False,  True, False,  True,
         True],
       [False,  True,  True, False, False,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [ True, False, False,  True, False,  True, False,  True,  True,
         True]])

In [57]:
m > 8

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True, False,  True, False, False, False, False,
        False],
       [ True,  True, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False,  True, False, False,  True, False, False,
        False],
       [False,  True, False, False, False,  True, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False]])

In [58]:
m[m < 5]

array([4, 2, 1, 4, 3, 2, 4, 4, 2, 2, 3, 3, 1, 4, 2, 4, 3, 3, 1, 4, 1, 1,
       2, 2, 3, 3, 1, 3, 4, 4, 1, 4, 3, 1, 2, 2, 2, 4, 3, 2, 1, 4, 4])

In [59]:
m[m > 3]

array([4, 8, 8, 6, 6, 6, 7, 4, 8, 4, 7, 4, 6, 9, 9, 7, 5, 7, 9, 6, 9, 9,
       9, 8, 8, 5, 9, 4, 4, 8, 7, 6, 8, 4, 6, 7, 6, 7, 4, 4, 6, 7, 9, 6,
       4, 7, 7, 6, 5, 8, 6, 9, 8, 6, 9, 7, 9, 5, 5, 9, 6, 7, 6, 4, 7, 9,
       8, 6, 4, 4])

In [60]:
# filter used in data analysis
m[(m > 3) & (m <=6)]

array([4, 6, 6, 6, 4, 4, 4, 6, 5, 6, 5, 4, 4, 6, 4, 6, 6, 4, 4, 6, 6, 4,
       6, 5, 6, 6, 5, 5, 6, 6, 4, 6, 4, 4])

In [61]:
# numpy documents
m.flatten?

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()